namespace db2k;

class Resources {
	public static string[] index_html= [
		"<!DOCTYPE html>",
		"<html>",
		"<head>",
		"    <script>",
		"//#insertjspoint",
		"    </script>",
		"</head>",
		"<body style=\"margin: 0px; background-color: black; color: white;\">",
		"    <canvas id=\"maincanvas\" style=\"display: block; position: absolute; width:100%; height: 100%\"></canvas>",
		"    <div id=\"progressdiv\" style=\"position: fixed; align-content: center; align-items: center; width: 100%; height: 100%;\">",
		"        <p id=\"progresstext\" style=\"text-align: center;\" >Loading:</p>",
		"    </div>",
		"</body>",
		"</html>",
	];

	public static string[] main_js= [
		"const screenRatio = 1920/1080;",
		"",
		"const vertexShaderText= ",
		"\"#version 300 es\\n\" +",
		"\"precision mediump float;\\n\" +",
		"\"in vec2 a_position;\\n\" +",
		"\"void main()\\n\" +",
		"\"{\\n\"  +",
		"\"    gl_Position = vec4(a_position, 0, 1);\\n\" +",
		"\"}\\n\";",
		"",
		"",
		"const fragmentShaderTextPre =",
		"`#version 300 es",
		"precision mediump float;",
		"",
		"out vec4 _outColor;",
		"uniform vec3 iResolution;",
		"uniform int iFrame;",
		"uniform float iTime;",
		"",
		"`;",
		"",
		"const fragmentShaderTextPost= ",
		"`",
		"void main() {",
		" mainImage( _outColor, gl_FragCoord.xy );",
		"}",
		"`;",
		"",
		"",
		"var shaderInitFailed = false;",
		"",
		"//#insertdatapoint",
		"",
		"//#insertsplashpoint",
		"",
		"class GLUniform {",
		"",
		"    constructor(gl, prg, name, suffix) {",
		"        this.gl = gl;",
		"        this.name = name;",
		"        this.suffix = suffix;",
		"        this.location = this.gl.getUniformLocation(prg, name);",
		"    }",
		"",
		"    set(...values) {",
		"        let method = \"uniform\" + this.suffix;",
		"        let args = [this.location].concat(values);",
		"        this.gl[method].apply(this.gl, args);",
		"    }",
		"}",
		"",
		"class GLProgram {",
		"    constructor(gl, vertexShaderText, vertexShaderSourceMap, fragmentShaderText, fragmentShaderSourceMap) {",
		"        this.gl = gl;",
		"        this.prg = this.gl.createProgram();",
		"        this.addShader(vertexShaderText, vertexShaderSourceMap, this.gl.VERTEX_SHADER);",
		"        this.addShader(fragmentShaderText, fragmentShaderSourceMap, this.gl.FRAGMENT_SHADER);",
		"",
		"        this.gl.linkProgram(this.prg);",
		"",
		"        if (!this.gl.getProgramParameter(this.prg, this.gl.LINK_STATUS)) {",
		"            const info = this.gl.getProgramInfoLog(this.prg);",
		"            throw `Could not compile WebGL program. \\n\\n${info}`;",
		"        }",
		"",
		"",
		"",
		"        this.gl.useProgram(this.prg);",
		"",
		"        this.time = new GLUniform(this.gl,this.prg, \"iTime\", \"1f\");",
		"        this.frame = new GLUniform(this.gl, this.prg, \"iFrame\", \"1i\");",
		"        this.resolution = new GLUniform(this.gl, this.prg, \"iResolution\", \"3f\");",
		"        this.textureUniforms = [];",
		"    }",
		"",
		"    updateRes( width, height )",
		"    {",
		"        this.resolution.set(width, height, 1);",
		"    }",
		"",
		"    addShader(source, sourceMap, type) {",
		"        let shader = this.gl.createShader(type);",
		"        this.gl.shaderSource(shader, source);",
		"        this.gl.compileShader(shader);",
		"        let isCompiled = this.gl.getShaderParameter(shader, this.gl.COMPILE_STATUS);",
		"",
		"",
		"        if (!isCompiled) {",
		"            let errs = [];",
		"            let er = this.gl.getShaderInfoLog(shader);",
		"",
		"            let reg = /^ERROR: (\\d+):(\\d+): (.+)$/;",
		"",
		"            for (let ln of er.split(\"\\n\")) {",
		"                let m = reg.exec(ln);",
		"                if (m != null) {",
		"                    let lineNum = m[2];",
		"                    let columnNum = m[1];",
		"                    let errorMessage = m[3];",
		"",
		"                    for (let sm of sourceMap) {",
		"                        let smFile = sm[0];",
		"                        let smStart = sm[1];",
		"                        let smEnd = sm[2];",
		"                        let smSrc = sm[3];",
		"",
		"                        if (lineNum >= smStart && lineNum <= smEnd) {",
		"                            errs.push(`Error: ${smFile}:${lineNum - smStart + smSrc}:${columnNum}: ${errorMessage}`);",
		"                        }",
		"                    }",
		"                }",
		"            }",
		"",
		"            throw new Error(`Shader compile errors:\\n${errs.join('\\n')}`);",
		"        }",
		"",
		"        this.gl.attachShader(this.prg, shader);",
		"    }",
		"",
		"    ",
		"",
		"    addTexture(name, width, height, uint8Array)",
		"    {",
		"        var texture = this.gl.createTexture();",
		"        this.gl.activeTexture(this.gl.TEXTURE0 + this.textureUniforms.length);",
		"        this.gl.bindTexture(this.gl.TEXTURE_2D, texture);",
		"        this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_MAG_FILTER, this.gl.LINEAR);",
		"        this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_MIN_FILTER, this.gl.LINEAR);",
		"",
		"",
		"        this.gl.texImage2D(",
		"            this.gl.TEXTURE_2D,",
		"            0,",
		"            this.gl.RGBA,",
		"            width, height,",
		"            0,",
		"            this.gl.RGBA, this.gl.UNSIGNED_BYTE,",
		"            uint8Array",
		"        );",
		"",
		"        var nu = new GLUniform(this.gl, this.prg, name, \"1i\");",
		"        nu.set(this.textureUniforms.length);",
		"        this.textureUniforms.push(nu);",
		"        // this.gl.generateMipmap(this.gl.TEXTURE_2D);",
		"    }",
		"    use() {",
		"        this.gl.useProgram(this.prg);",
		"    }",
		"}",
		"",
		"class GLRect {",
		"    constructor( gl ) {",
		"        this.gl= gl;",
		"        this.verts = new Float32Array([-1, -1, 1, -1, -1, 1, 1, 1]);",
		"",
		"        let buffer = this.gl.createBuffer();",
		"        this.gl.bindBuffer(this.gl.ARRAY_BUFFER, buffer);",
		"        this.gl.bufferData(this.gl.ARRAY_BUFFER, this.verts, this.gl.STATIC_DRAW);",
		"    }",
		"",
		"    render() {",
		"        this.gl.drawArrays(this.gl.TRIANGLE_STRIP, 0, 4);",
		"    }",
		"}",
		"",
		"function isBuiltIn(info) {",
		"    const name = info.name;",
		"    return name.startsWith(\"gl_\") || name.startsWith(\"webgl_\");",
		"}",
		"",
		"",
		"function glEnumToString(gl, value) {",
		"    const keys = [];",
		"    for (const key in gl) {",
		"        if (gl[key] === value) {",
		"            keys.push(key);",
		"        }",
		"    }",
		"    return keys.length ? keys.join(' | ') : `0x${value.toString(16)}`;",
		"}",
		"",
		"function dumpGLProgram(gl, prg) {",
		"    var output = '';",
		"    var shaders = gl.getAttachedShaders(prg);",
		"",
		"    output += `program",
		"  #shaders: ${shaders.length}",
		"`;",
		"",
		"    {",
		"        output += 'Uniforms:'",
		"        const numUniforms = gl.getProgramParameter(prg, gl.ACTIVE_UNIFORMS);",
		"        const indices = [...Array(numUniforms).keys()];",
		"        const blockIndices = gl.getActiveUniforms(prg, indices, gl.UNIFORM_BLOCK_INDEX);",
		"        const offsets = gl.getActiveUniforms(prg, indices, gl.UNIFORM_OFFSET);",
		"",
		"        for (let ii = 0; ii < numUniforms; ++ii) {",
		"            const uniformInfo = gl.getActiveUniform(prg, ii);",
		"            if (isBuiltIn(uniformInfo)) {",
		"                continue;",
		"            }",
		"            const { name, type, size } = uniformInfo;",
		"            const blockIndex = blockIndices[ii];",
		"            const offset = offsets[ii];",
		"",
		"            output += `${name} ${glEnumToString(gl, type)}\\n`;",
		"        }",
		"",
		"    }",
		"",
		"    return output;",
		"}",
		"",
		"",
		"function dumpGL( gl ) {",
		"    var output = 'dumping OpenGL\\n';",
		"    var prg = gl.getParameter(gl.CURRENT_PROGRAM);",
		"",
		"",
		"    if (prg == null)",
		"        output += 'No active program\\n';",
		"    else",
		"        output += dumpGLProgram(gl, prg);",
		"",
		"    console.log(output);",
		"}",
		"",
		"var offScreenWidth= 1920;",
		"var offScreenHeight= 1080;",
		"",
		"class ShaderScreen",
		"{",
		"    init()",
		"    {",
		"        this.texturesLoaded = 0;",
		"",
		"        this.windowWidth= 0;",
		"        this.windowHeight= 0;",
		"        this.width= 0;",
		"        this.height= 0;",
		"",
		"        this.shaderCanvas = document.getElementById(\"maincanvas\");",
		"",
		"       this.gl = this.shaderCanvas.getContext(\"webgl2\", { preserveDrawingBuffer: true });",
		"        this.billboard = new GLRect(this.gl);",
		"",
		"        this.shaderProgramError = null;",
		"",
		"        dumpGL(this.gl);",
		"    }",
		"",
		"    /*",
		"    initShaderProgram(fragmentShaderText, fragmentShaderSourceMap)",
		"    {",
		"        this.fragmentShaderText = fragmentShaderText;",
		"        try {",
		"            this.shaderProgram = new GLProgram(this.gl, vertexShaderText, [], this.fragmentShaderText, fragmentShaderSourceMap);",
		"",
		"        }",
		"        catch (e) {",
		"            console.log(e);",
		"            this.shaderProgramError = e;",
		"        }",
		"    }",
		"    */",
		"",
		"    initTextures() {",
		"        var loadedCount = 0;",
		"        var canv = document.createElement('canvas');",
		"        var _this = this;",
		"",
		"        shaders.forEach(sh => {",
		"            textures.forEach(t => {",
		"                var name = t[0];",
		"                var dataUri = \"data:text/plain;base64,\" + t[1];",
		"",
		"                const img = new Image();",
		"                img.onload = function () {",
		"",
		"                    const ctx = canv.getContext('2d');",
		"                    canv.width = img.width;",
		"                    canv.height = img.height;",
		"",
		"                    // Draw the image onto the canvas",
		"                    ctx.drawImage(img, 0, 0, img.width, img.height);",
		"",
		"                    // Get the image data, which is a Uint8ClampedArray (RGBA bytes)",
		"                    const imageData = ctx.getImageData(0, 0, img.width, img.height);",
		"                    const byteArray = imageData.data;",
		"",
		"                    _this.shaderProgram.addTexture(name, img.width, img.height, byteArray);",
		"                    loadedCount++;",
		"                };",
		"                img.src = dataUri;",
		"            });",
		"        });",
		"    }",
		"",
		"    Present( currentTime, currentFrame, shader )",
		"    {",
		"        var ww = window.innerWidth;",
		"        var wh = window.innerHeight;",
		"        if (ww != this.windowWidth || wh != this.windowHeight) {",
		"            this.windowWidth = ww;",
		"            this.windowHeight = wh;",
		"            this.shaderCanvas.setAttribute(\"width\", this.windowWidth);",
		"            this.shaderCanvas.setAttribute(\"height\", this.windowHeight);",
		"            shader.updateRes(this.windowWidth, this.windowHeight);",
		"",
		"            this.gl.viewport(0, 0, this.windowWidth, this.windowHeight);",
		"        }",
		"",
		"        let positionLocation = this.gl.getAttribLocation(shader.prg, \"a_position\");",
		"        this.gl.enableVertexAttribArray(positionLocation);",
		"        this.gl.vertexAttribPointer(positionLocation, 2, this.gl.FLOAT, false, 0, 0);",
		"",
		"        this.gl.enable(this.gl.BLEND);",
		"        this.gl.blendFunc(this.gl.ONE, this.gl.ZERO);",
		"",
		"",
		"        //var corr = 1.5;",
		"        //var ww = this.shaderCanvas.width;",
		"        //var wh = this.shaderCanvas.height;",
		"",
		"",
		"        // shader.prg.use();",
		"        this.gl.useProgram(shader.prg);",
		"",
		"        shader.time.set(currentTime/1000.0);",
		"        shader.frame.set(currentFrame);",
		"        ",
		"",
		"        this.billboard.render();",
		"    }",
		"}",
		"",
		"function initShaders()",
		"{",
		"    if (shaderInitFailed)",
		"        return;",
		"",
		"    for (var sh of shaders)",
		"    {",
		"        var index = sh.index;",
		"        var text = fragmentShaderTextPre + sh.text + fragmentShaderTextPost;",
		"",
		"        var prg = new GLProgram(screen.gl, vertexShaderText, \"\", text, \"\");",
		"",
		"        sh.program = prg;",
		"    }",
		"}",
		"",
		"function sleep() {",
		"//    var now = new Date().getTime();",
		"//    while (new Date().getTime() < now + 1000*4) { /* Do nothing */ };",
		"}",
		"function rsleep() {",
		"    var now = new Date().getTime();",
		"    while (new Date().getTime() < now + 1000*4) { /* Do nothing */ };",
		"}",
		"",
		"var screen = new ShaderScreen();",
		"var startTime = 0;",
		"var frame = 0;",
		"var stage = 0;",
		"var stageDesc = '';",
		"var error = null;",
		"var shadersLoadFailed = false;",
		"var curShader = 0;",
		"",
		"",
		"//#ifdef MONITOR",
		"setInterval(() => {",
		"    fetch(\"http://localhost:6969/updated\")",
		"        .then(r => {",
		"            if (r.status == 205) {",
		"                console.log('reload!!!!!');",
		"                window.location.reload();",
		"            }",
		"        });",
		"}, 1000);",
		"//#endif",
		"",
		"var snd = new Sound();",
		"",
		"snd.load(audioData);",
		"",
		"",
		"",
		"",
		"var stages = [",
		"    ['finishing load', (timeMs) => {",
		"        if( document.getElementById('maincanvas') )",
		"            stage++",
		"    }], ",
		"    ['initialising screen', (timeMs) => { screen.init(); sleep(); stage++; }],",
		"    ['initialising shaders', (timeMs) => {",
		"",
		"",
		"",
		"        if (screen.shaderProgramError == null)",
		"        {",
		"            initShaders();",
		"",
		"            //screen.initShaderProgram(fragmentShaderText, sourceMap);",
		"",
		"            //if (screen.shaderProgramError != null) {",
		"            //    document.getElementById('progresstext').innerText = screen.shaderProgramError.stack;",
		"            //    return;",
		"            //}",
		"",
		"//#ifdef USEUNIFORMS",
		"            initUniforms();",
		"//#endif",
		"            sleep();",
		"            stage++;",
		"        }",
		"    }],",
		"    ['loading textures', (timeMs) => {",
		"        // screen.initTextures();",
		"        sleep(); stage++;",
		"    }],",
		"//#ifdef USERWAIT",
		"    ['displaying splash screen', (timeMs) => {",
		"        var pd= document.getElementById('progressdiv');",
		"        pd.innerHTML = splashHtml;",
		"        pd.onclick = () => {",
		"            document.getElementById(\"progressdiv\").remove(); ",
		"            snd.play();",
		"            stage++;",
		"        }",
		"        stage++;",
		"    }],",
		"    ['waiting for user input', (timeMs) => {",
		"    }],",
		"//#else",
		"    ['removing progress bar', (timeMs) => {",
		"        document.getElementById(\"progressdiv\").remove(); ",
		"        snd.play();",
		"        stage++;",
		"    }],",
		"//#endif",
		"    ['marking start time', (timeMs) =>",
		"        {",
		"            startTime = timeMs;",
		"            stage++;",
		"        }",
		"    ],",
		"    ['running intro', (timeMs) => {",
		"        var ut = timeMs - startTime;",
		"",
		"//#ifdef USEJAVASCRIPT",
		"        update(frame, ut/1000.0);",
		"//#endif",
		"        screen.Present(ut, frame, shaders[curShader].program);",
		"",
		"//#ifdef MONITOR",
		"        if (frame == 10)",
		"            fetch(\"http://localhost:6969/testfinished\");",
		"//#endif",
		"",
		"        frame++;",
		"    }]",
		"];",
		"",
		"",
		"function animate(timeMs) ",
		"{",
		"    var e = document.getElementById(\"progresslabel\");",
		"    var mc = document.getElementById('maincanvas');",
		"    var st = stages[stage];",
		"",
		"    if (e != null && mc != null)",
		"    {",
		"        var txt;",
		"        if (st[0] != null)",
		"            txt = st[0];",
		"",
		"        e.innerText = txt;",
		"    }",
		"",
		"    st[1](timeMs);",
		"",
		"",
		"    requestAnimationFrame(animate);",
		"}",
		"    ",
		"animate(0);",
	];

	public static string[] sound_mp3_js= [
		"",
		"class Sound {",
		"",
		"    buffer = null;",
		"",
		"    sources = [];",
		"",
		"    constructor() {",
		"    }",
		"",
		"    load(b64string) {",
		"        var buff = Uint8Array.fromBase64(b64string);",
		"        audioContext.decodeAudioData(buff.buffer, (buffer) => {",
		"            if (!buffer) {",
		"                console.log(`Sound decoding error: ${this.url}`);",
		"                reject(new Error(`Sound decoding error: ${this.url}`));",
		"                return;",
		"            }",
		"",
		"            this.buffer = buffer;",
		"        });",
		"    }",
		"",
		"    play(volume = 1, time = 0) {",
		"        if (!this.buffer) return;",
		"",
		"        const source = audioContext.createBufferSource();",
		"        source.buffer = this.buffer;",
		"        const insertedAt = this.sources.push(source) - 1;",
		"        source.onended = () => {",
		"            source.stop(0);",
		"",
		"            this.sources.splice(insertedAt, 1);",
		"        };",
		"        const gainNode = audioContext.createGain();",
		"        gainNode.gain.value = volume;",
		"        source.connect(gainNode).connect(audioContext.destination);",
		"        source.loop = true;",
		"        source.start(time);",
		"    }",
		"",
		"    stop() {",
		"        this.sources.forEach((source) => {",
		"            source.stop(0);",
		"        });",
		"",
		"        this.sources = [];",
		"    }",
		"}",
		"",
		"const audioContext = new AudioContext();",
		"",
	];

	public static string[] sound_null_js= [
		"class Sound {",
		"",
		"    load(arg) {",
		"",
		"    }",
		"    play() {",
		"",
		"    }",
		"}",
	];

	public static void Init()
	{
		string resDir= Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location), "..\\..\\..\\res");
		if(Directory.Exists(resDir))
		{
			index_html = File.ReadAllLines(Path.Combine(resDir,"index.html"));
			main_js = File.ReadAllLines(Path.Combine(resDir,"main.js"));
			sound_mp3_js = File.ReadAllLines(Path.Combine(resDir,"sound_mp3.js"));
			sound_null_js = File.ReadAllLines(Path.Combine(resDir,"sound_null.js"));
		}
	}
}
